### ISSUE TITLE
How long will the verilator-based simulation take?

### ISSUE THREAD

**Issue by HaFred** [rbshi/elstm#2]
Hi @rbshi,
It seems to me the paper is doing spike simulation, which assumes every instruction is done in one clock cycle. I wonder what is the performance in terms of the cycle-accurate RTL simulator, the verilator? Thank you very much!

**Comment by rbshi** [comment]
Hi @HaFred 
Sorry for late reply. The paper results were dumped by Spike, Yes. But the instruction execution time is NOT one cycle, for the ELSTM accelerator on ROCC interface. Actually, I added a variable [`clock`](https://github.com/riscv/riscv-isa-sim/blob/a4dd74abd631e7d4d46d956720abeb857d19afc0/elstm_rocc/elstm_rocc.cc#L65) in the accelerator description file. During simulating each cycle, `clock++`. 
Regrading to the real RTL implementation, you can find the ROCC interface has `READY` signal, with which the accelerator can indicate a `busy state` and the current ISA instruction will pending for multi cycles.

**Comment by HaFred** [comment]
> Hi @HaFred
> Sorry for late reply. The paper results were dumped by Spike, Yes. But the instruction execution time is NOT one cycle, for the ELSTM accelerator on ROCC interface. Actually, I added a variable [`clock`](https://github.com/riscv/riscv-isa-sim/blob/a4dd74abd631e7d4d46d956720abeb857d19afc0/elstm_rocc/elstm_rocc.cc#L65) in the accelerator description file. During simulating each cycle, `clock++`.
> Regrading to the real RTL implementation, you can find the ROCC interface has `READY` signal, with which the accelerator can indicate a `busy state` and the current ISA instruction will pending for multi cycles.

Thank you for your reply shek. So you meant you rebuilt the spike with the incrementing clock to simulate the how will each instruction go through the pipeline like they do in real RTL? I cannot get any clue from the paper on RTL implementation so I am just curious.                                                                                                                      
                                                                                                                                                                                
Besides, I would like to know how did you come out with the `eSELL sparse matrix format was developed that reduces the area cost of the on-chip buﬀer by 63%` in the paper, I know the eSELL makes the coalescing access just like CUDA, which may definitely be superior, but I just cannot figure out where the number `63%` comes from.    
                                                                                                                                                                                   Thank you in advance for your precious time.

**Comment by rbshi** [comment]
> > Hi @HaFred
> > Sorry for late reply. The paper results were dumped by Spike, Yes. But the instruction execution time is NOT one cycle, for the ELSTM accelerator on ROCC interface. Actually, I added a variable [`clock`](https://github.com/riscv/riscv-isa-sim/blob/a4dd74abd631e7d4d46d956720abeb857d19afc0/elstm_rocc/elstm_rocc.cc#L65) in the accelerator description file. During simulating each cycle, `clock++`.
> > Regrading to the real RTL implementation, you can find the ROCC interface has `READY` signal, with which the accelerator can indicate a `busy state` and the current ISA instruction will pending for multi cycles.
> 
> Thank you for your reply shek. So you meant you rebuilt the spike with the incrementing clock to simulate the how will each instruction go through the pipeline like they do in real RTL? I cannot get any clue from the paper on RTL implementation so I am just curious.
> 
> Besides, I would like to know how did you come out with the `eSELL sparse matrix format was developed that reduces the area cost of the on-chip buﬀer by 63%` in the paper, I know the eSELL makes the coalescing access just like CUDA, which may definitely be superior, but I just cannot figure out where the number `63%` comes from.
> Thank you in advance for your precious time.

* Yes, the behavior of accelerator is relatively simple and the simulator can surely give a reliable number. Yes, as the Sec.4.1 says, simulation only. 
* Please refer to Sec.3.1.1, the SRAM area is proportional to (port number)^0.7. Before applying eSELL: 4 ports; after: 1 port. Then the reduction can be evaluated with (1-1/(4^0.7)). 

BTW, this paper aims to propose a SpMV (main workload of RNN) design scheme that saves both interface and SRAM cost (e.g., the RISC-V centric scenario with interface constraint). It's not an out-of-the-box implementation. If you want to realize it on-chip, probably I can provide some extra suggestion. 

Thanks for your interest.
